version: '3'
services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    ports:
      - '27017:27017'

  app:
    container_name: epgpweb-server
    build: .
    working_dir: /usr/src/app
    ports:
      - '80:3000'
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run start:prod
